### ISSUE TITLE
Fixed: Task 7 rejected, uses call instead of send

### ISSUE THREAD

**Issue by e00dan** [Soptq/2021-Nervos-Broaden-the-Spectrum-task7#2]
Call is readonly and doesn't change smart-contract state.

Send is used to change state of smart-contracts.

```
createTask: async (title, description) => {
		try {
			const result = await App.tasksContract.methods.createTask(title, description).call({
				gas: 6000000,
				from: App.account,
			});
			alert("After the transaction completes, please refresh the webpage.")
		} catch (error) {
			console.error(error);
		}
	},
```

**Comment by Soptq** [comment]
> Call is readonly and doesn't change smart-contract state.
> 
> Send is used to change state of smart-contracts.
> 
> ```
> createTask: async (title, description) => {
> 		try {
> 			const result = await App.tasksContract.methods.createTask(title, description).call({
> 				gas: 6000000,
> 				from: App.account,
> 			});
> 			alert("After the transaction completes, please refresh the webpage.")
> 		} catch (error) {
> 			console.error(error);
> 		}
> 	},
> ```

Fixed! Thanks for helping!

**Comment by Soptq** [comment]
@kuzirashi Currently there are only 120 submissions for Task 7, hope this repo can be considered as a resubmission after fixing call/send issue, rather than rejection. Really appreciate your reviewing, thank you! 😄
